apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        resolver 10.96.0.10 valid=5s;
        location /orders/ {
          set $upstream http://order-service.default.svc.cluster.local:8081;
          proxy_pass $upstream/;
        }
        location /payments/ {
          set $upstream http://payment-service.default.svc.cluster.local:8082;
          proxy_pass $upstream/;
        }
        location /shipping/ {
          set $upstream http://shipping-service.default.svc.cluster.local:8083;
          proxy_pass $upstream/;
        }
        location / {
          set $upstream http://frontend-service.default.svc.cluster.local:80;
          proxy_pass $upstream$request_uri;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
