spring.application.name=user-service
server.port=8083

aws.dynamodb.endpoint=http://localhost:4566
aws.dynamodb.region=us-east-1
aws.dynamodb.accessKey=test
aws.dynamodb.secretKey=test
aws.dynamodb.tableName=Usuarios
